<?php

define(PERM_CONT_UPDATE,	1);

define(PERM_PAIS_LIST,		2);
define(PERM_PAIS_CREATE,	3);
define(PERM_PAIS_DELETE,	4);
define(PERM_PAIS_UPDATE,	5);

define(PERM_PROV_LIST,		6);
define(PERM_PROV_CREATE,	7);
define(PERM_PROV_DELETE,	8);
define(PERM_PROV_UPDATE,	9);

define(PERM_PART_LIST,		10);
define(PERM_PART_CREATE,	11);
define(PERM_PART_DELETE,	12);
define(PERM_PART_UPDATE,	13);

define(PERM_LOCA_LIST,		14);
define(PERM_LOCA_CREATE,	15);
define(PERM_LOCA_DELETE,	16);
define(PERM_LOCA_UPDATE,	17);

define(PERM_COLO_LIST,		18);
define(PERM_COLO_CREATE,	19);
define(PERM_COLO_DELETE,	20);
define(PERM_COLO_UPDATE,	21);

define(PERM_MARC_LIST,		22);
define(PERM_MARC_CREATE,	23);
define(PERM_MARC_DELETE,	24);
define(PERM_MARC_UPDATE,	25);

define(PERM_UBIC_LIST,		26);
define(PERM_UBIC_CREATE,	27);
define(PERM_UBIC_DELETE,	28);
define(PERM_UBIC_UPDATE,	29);

define(PERM_ESTU_LIST,		30);
define(PERM_ESTU_CREATE,	31);
define(PERM_ESTU_DELETE,	32);
define(PERM_ESTU_UPDATE,	33);

define(PERM_ESTC_LIST,		34);
define(PERM_ESTC_CREATE,	35);
define(PERM_ESTC_DELETE,	36);
define(PERM_ESTC_UPDATE,	37);

define(PERM_TIPM_LIST,		38);
define(PERM_TIPM_CREATE,	39);
define(PERM_TIPM_DELETE,	40);
define(PERM_TIPM_UPDATE,	41);

define(PERM_TIPD_LIST,		42);
define(PERM_TIPD_CREATE,	43);
define(PERM_TIPD_DELETE,	44);
define(PERM_TIPD_UPDATE,	45);

define(PERM_TIPI_LIST,		46);
define(PERM_TIPI_CREATE,	47);
define(PERM_TIPI_DELETE,	48);
define(PERM_TIPI_UPDATE,	49);

define(PERM_PROF_LIST,		50);
define(PERM_PROF_CREATE,	51);
define(PERM_PROF_DELETE,	52);
define(PERM_PROF_UPDATE,	53);

define(PERM_MODU_LIST,		54);
define(PERM_MODU_CREATE,	55);
define(PERM_MODU_DELETE,	56);
define(PERM_MODU_UPDATE,	57);
define(PERM_MODU_PERMS,		58);

define(PERM_PERF_LIST,		59);
define(PERM_PERF_CREATE,	60);
define(PERM_PERF_DELETE,	61);
define(PERM_PERF_UPDATE,	62);
define(PERM_PERF_PERMS,		63);

define(PERM_SECT_LIST,		64);
define(PERM_SECT_CREATE,	65);
define(PERM_SECT_DELETE,	66);
define(PERM_SECT_UPDATE,	67);

define(PERM_USUA_LIST,		68);
define(PERM_USUA_CREATE,	69);
define(PERM_USUA_DELETE,	70);
define(PERM_USUA_UPDATE,	71);

define(PERM_CLIE_LIST,		72);
define(PERM_CLIE_CREATE,	73);
define(PERM_CLIE_DELETE,	74);
define(PERM_CLIE_UPDATE,	75);
define(PERM_CLIE_CONTACTS,	76);

define(PERM_MODE_LIST,		77);
define(PERM_MODE_CREATE,	78);
define(PERM_MODE_DELETE,	79);
define(PERM_MODE_UPDATE,	80);
define(PERM_MODE_IMPORT,	81);

define(PERM_UNID_LIST,		82);
define(PERM_UNID_CREATE,	83);
define(PERM_UNID_DELETE,	84);
define(PERM_UNID_UPDATE,	85);

define(PERM_VENT_LIST,		86);
define(PERM_VENT_CREATE,	87);
define(PERM_VENT_DELETE,	88);
define(PERM_VENT_UPDATE,	89);

define(PERM_REMI_LIST,		90);
define(PERM_REMI_CREATE,	91);
define(PERM_REMI_DELETE,	92);
define(PERM_REMI_PRINT,		93);

define(PERM_COMP_LIST,		94);
define(PERM_COMP_CREATE,	95);
define(PERM_COMP_DELETE,	96);
define(PERM_COMP_UPDATE,	97);

define(PERM_RECE_LIST,		98);
define(PERM_RECE_CREATE,	99);
define(PERM_RECE_DELETE,	100);
define(PERM_RECE_UPDATE,	101);

define(PERM_CMPB_LIST,		102);
define(PERM_CMPB_CREATE,	103);
define(PERM_CMPB_UPDATE,	104);

define(PERM_FACU_LIST,		105);
define(PERM_FACU_CREATE,	106);
define(PERM_FACU_DELETE,	107);
define(PERM_FACU_UPDATE,	108);

define(PERM_FACV_LIST,		109);
define(PERM_FACV_CREATE,	110);
define(PERM_FACV_DELETE,	111);
define(PERM_FACV_UPDATE,	112);

define(PERM_CATM_LIST,		113);
define(PERM_CATM_CREATE,	114);
define(PERM_CATM_DELETE,	115);
define(PERM_CATM_UPDATE,	116);

define(PERM_ORDS_LIST,		117);
define(PERM_ORDS_CREATE,	118);
define(PERM_ORDS_DELETE,	119);

define(PERM_NONR_LIST,		120);
define(PERM_NONR_CREATE,	121);
define(PERM_NONR_DELETE,	122);

define(PERM_PACC_LIST,		123);
define(PERM_PACC_CREATE,	124);
define(PERM_PACC_DELETE,	125);
define(PERM_PACC_UPDATE,	126);

define(PERM_FORM_LIST,		127);
define(PERM_FORM_CREATE,	128);
define(PERM_FORM_DELETE,	129);
define(PERM_FORM_UPDATE,	130);

define(PERM_GEST_LIST,		131);
define(PERM_GEST_CREATE,	132);
define(PERM_GEST_DELETE,	133);
define(PERM_GEST_UPDATE,	134);

define(PERM_IPRE_LIST,		135);
define(PERM_IPRE_CREATE,	136);
define(PERM_IPRE_DELETE,	137);
define(PERM_IPRE_UPDATE,	138);

define(PERM_PLAV_LIST,		139);
define(PERM_PLAV_CREATE,	140);
define(PERM_PLAV_DELETE,	141);
define(PERM_PLAV_UPDATE,	142);

define(PERM_REPF_LIST,		143);
define(PERM_REPF_CREATE,	144);
define(PERM_REPF_DELETE,	145);
define(PERM_REPF_UPDATE,	146);

define(PERM_ALER_LIST,		147);

define(PERM_ACRE_LIST,		148);
define(PERM_ACRE_CREATE,	149);
define(PERM_ACRE_DELETE,	150);
define(PERM_ACRE_UPDATE,	151);

define(PERM_ARTI_LIST,		152);
define(PERM_ARTI_CREATE,	153);
define(PERM_ARTI_DELETE,	154);
define(PERM_ARTI_UPDATE,	155);

define(PERM_RUBR_LIST,		156);
define(PERM_RUBR_CREATE,	157);
define(PERM_RUBR_DELETE,	158);
define(PERM_RUBR_UPDATE,	159);

define(PERM_PROVE_LIST,		160);
define(PERM_PROVE_CREATE,	161);
define(PERM_PROVE_DELETE,	162);
define(PERM_PROVE_UPDATE,	163);

define(PERM_ARTI_LIST,		164);
define(PERM_ARTI_CREATE,	165);
define(PERM_ARTI_DELETE,	166);
define(PERM_ARTI_UPDATE,	167);

define(PERM_STOCK_LIST,		168);
define(PERM_STOCK_CREATE,	169);
define(PERM_STOCK_DELETE,	170);
define(PERM_STOCK_UPDATE,	171);

define(PERM_TALL_LIST,		172);
define(PERM_TALL_CREATE,	173);

define(PERM_TARE_LIST,		174);
define(PERM_TARE_CREATE,	175);
define(PERM_TARE_UPDATE,	176);
define(PERM_TARE_DELETE,	177);

define(PERM_ORDE_LIST,		178);
define(PERM_ORDE_CREATE,	179);
define(PERM_ORDE_UPDATE,	180);
define(PERM_ORDE_DELETE,	181);

define(PERM_TALL_REPORTES,	182);
define(PERM_STOCK_REPORTES,	183);

define(PERM_STOCK_AJUSTE,	184);

define(PERM_CUPON_LIST,		185);
define(PERM_CUPON_CREATE,	186);
define(PERM_CUPON_UPDATE,	187);

define(PERM_STOCK_UNIDADES, 188);
define(PERM_ORDE_TALLER, 	189);

define(PERM_COMPRA_LIST, 	190);
define(PERM_COMPRA_CREATE,  191);
define(PERM_COMPRA_EXPORTAR, 192);

define(PERM_LIBRO_IVA, 		193);

define(PERM_UNID_PISAR,		194);
define(PERM_UNID_REPARAR,	195);

define(PERM_CPRE_LIST,		196);
define(PERM_CPRE_CREATE,	197);
define(PERM_CPRE_UPDATE,	198);
define(PERM_CPRE_REPORT,	199);

define(PERM_MINP_LIST,		200);
define(PERM_MINP_CREATE,	201);
define(PERM_MINP_UPDATE,	202);

define(PERM_TAREAS_LIST,	203);
define(PERM_TAREAS_CREATE,	204);
define(PERM_TAREAS_DELETE,	205);
define(PERM_TAREAS_UPDATE,	206);

define(PERM_PRESUP_LIST,	207);
define(PERM_PRESUP_CREATE,	208);
define(PERM_PRESUP_UPDATE,	209);
define(PERM_PRESUP_DELETE,	210);

define(PERM_UNID_STOCK,		211);

define(PERM_VENTUS_LIST,	212);
define(PERM_VENTUS_CREATE,	213);
define(PERM_VENTUS_UPDATE,	214);
define(PERM_VENTUS_DELETE,	215);

define(PERM_RECEPUS_LIST,	216);
define(PERM_RECEPUS_CREATE,	217);
define(PERM_RECEPUS_UPDATE,	218);
define(PERM_RECEPUS_DELETE,	219);

define(PERM_USADOS_LIST,	220);
define(PERM_USADOS_UPDATE,	221);
define(PERM_USADOS_DELETE,	222);
define(PERM_USADOS_REPORT,	223);
define(PERM_USADOS_PISAR,	224);

define(PERM_COMIS_LIST,		225);
define(PERM_VENT_REPORT,	226);

define(PERM_CUECOR_LIST,	227);
define(PERM_CUECOR_DETAIL,	228);

define(PERM_PAGO_LIST,		229);
define(PERM_PAGO_CREATE,	230);
define(PERM_PAGO_UPDATE,	231);
define(PERM_PAGO_DELETE,	232);

define(PERM_RETEN_REPORT,	233);

define(PERM_GESTOR_LIST,	234);
define(PERM_GESTOR_CREATE,	235);
define(PERM_GESTOR_UPDATE,	236);
define(PERM_GESTOR_DELETE,	237);

define(PERM_GESCUE_LIST,	238);
define(PERM_GESCUE_CREATE,	239);
define(PERM_GESCUE_UPDATE,	240);
define(PERM_GESCUE_DELETE,	241);
define(PERM_GESCUE_RENDICION,	242);


define(PERM_CPREUS_LIST,	243);
define(PERM_CPREUS_CREATE,	244);
define(PERM_CPREUS_UPDATE,	245);
define(PERM_CPREUS_DELETE,	246);
define(PERM_CPREUS_REPORT,	247);

define(PERM_FACTUS_LIST,	248);
define(PERM_FACTUS_CREATE,	249);
define(PERM_FACTUS_UPDATE,	250);
define(PERM_FACTUS_DELETE,	251);

define(PERM_CAJGES_LIST,	252);
define(PERM_CAJGES_CREATE,	253);
define(PERM_CAJGES_UPDATE,	254);
define(PERM_CAJGES_DELETE,	255);

define(PERM_PEDMAY_LIST,	256);
define(PERM_PEDMAY_CREATE,	257);
define(PERM_PEDMAY_UPDATE,	258);
define(PERM_PEDMAY_DELETE,	259);

define(PERM_PERIOD_LIST,	260);
define(PERM_PERIOD_UPDATE,	261);

define(PERM_UNID_REPORT,	262);

define(PERM_CODTRA_LIST,	263);
define(PERM_CODTRA_CREATE,	264);
define(PERM_CODTRA_UPDATE,	265);
define(PERM_CODTRA_DELETE,	266);

define(PERM_TURNO_LIST,		267);
define(PERM_TURNO_CREATE,	268);
define(PERM_TURNO_UPDATE,	269);
define(PERM_TURNOS_DELETE,	270);

define(PERM_FACTPV_LIST,	271);
define(PERM_FACTPV_CREATE,	272);
define(PERM_FACTPV_UPDATE,	273);
define(PERM_FACTPV_DELETE,	274);

define(PERM_ACTUALIZAR_PRECIO,	275);

define(PERM_CAJA_LIST,			276);
define(PERM_CAJA_CREATE,		277);
define(PERM_CAJA_UPDATE,		278);
define(PERM_CAJA_DELETE,		279);

define(PERM_CAJADEFT_LIST,		280);
define(PERM_CAJADEFT_CREATE,	281);

define(PERM_CHEQUE_LIST,		282);
define(PERM_CHEQUE_CREATE,		283);
define(PERM_CHEQUE_UPDATE,		284);
define(PERM_CHEQUE_DELETE,		285);
?>